### ISSUE TITLE
Nav bar links

### ISSUE THREAD

**Issue by cyber-chalk** [cyber-chalk/TD-00#15]
Currently, the nav links are not leading to anything.

Right- GitHub page
Left- settings (colours and stuff)

**Comment by BrendonW250** [comment]
Hi, may I ask what you would like the settings to be linked to?

**Comment by cyber-chalk** [comment]
Hi, The popup settings contain three inputs where the user can change the colour of each CSS variable (located in the CSS file). I tried to get this to work but was unsuccessful, you have to use getComputedStyles then getProperty value. I made a branch for this issue called "#15".

**Comment by cyber-chalk** [comment]
review #18

**Comment by cyber-chalk** [comment]
#19 Nav text needs to be filtered.
